# This file was generated by GoReleaser. DO NOT EDIT.
class Upm < Formula
  desc "Universal package manager: Python, Node.js, Ruby, Emacs Lisp."
  homepage "https://github.com/replit/upm"
  version "1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/replit/upm/releases/download/v1.0/upm_1.0_darwin_amd64.tar.gz"
    sha256 "5b9acaf69ad10a6847677b7625b931f3fad80e5b78ad84a78fd9c81074d36606"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/replit/upm/releases/download/v1.0/upm_1.0_linux_amd64.tar.gz"
      sha256 "3f02ccd8bf5d486f1809dc73566c9be41b265626ad0ca7b062d1739505a819b4"
    end
  end

  def install
    bin.install "upm"
  end

  test do
    assert_match "upm #{version.to_s}", shell_output("#{bin}/upm --version")
  end
end
